"""
AILEX Pilot — auto_pr_reviewer.py
Automatic PR review: AILEX analyses diffs and posts structured review comments.
"""
from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass, field
from typing import Any, List, Optional


@dataclass
class PRReview:
    pr_number:   int
    title:       str
    diff_summary: str
    issues:      List[str]
    suggestions: List[str]
    security:    List[str]
    verdict:     str   # "APPROVE" | "REQUEST_CHANGES" | "COMMENT"
    confidence:  float
    body:        str


class AutoPRReviewer:
    """Fetches PR diff, runs AILEX analysis, posts review via gh CLI."""

    def __init__(self, pipeline: Any):
        self.pipeline = pipeline

    def review_pr(self, pr_number: int, repo: str = "", post: bool = False) -> PRReview:
        diff     = self._get_diff(pr_number, repo)
        pr_info  = self._get_pr_info(pr_number, repo)
        title    = pr_info.get("title", f"PR #{pr_number}")

        request  = (
            f"Review this pull request: '{title}'\n\n"
            f"Diff summary (first 3000 chars):\n{diff[:3000]}\n\n"
            f"Focus on: bugs, security issues, code quality, missing tests, "
            f"breaking changes, performance regressions."
        )

        try:
            p, h, coda = self.pipeline.process(request, override_domain="code",
                                                include_context=False)
            report = self.pipeline.report(p, h, coda, fmt="full")
        except Exception as e:
            report = str(e)

        review = self._format_review(pr_number, title, diff, report, coda if 'coda' in dir() else None)

        if post:
            self._post_review(pr_number, review, repo)

        return review

    def _get_diff(self, pr_number: int, repo: str) -> str:
        cmd = ["gh", "pr", "diff", str(pr_number)]
        if repo:
            cmd += ["--repo", repo]
        r = subprocess.run(cmd, capture_output=True, text=True)
        return r.stdout[:6000] if r.returncode == 0 else ""

    def _get_pr_info(self, pr_number: int, repo: str) -> dict:
        cmd = ["gh", "pr", "view", str(pr_number), "--json", "title,body,author"]
        if repo:
            cmd += ["--repo", repo]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode == 0:
            import json
            try:
                return json.loads(r.stdout)
            except Exception:
                pass
        return {}

    def _format_review(self, pr_number: int, title: str, diff: str,
                        report: str, coda: Any) -> PRReview:
        conf    = getattr(coda, "final_confidence", 0.8) if coda else 0.8
        issues  = self._extract_issues(report)
        verdict = "REQUEST_CHANGES" if len(issues) > 2 else "APPROVE" if conf > 0.95 else "COMMENT"

        body = (
            f"## AILEX Automated PR Review\n\n"
            f"**PR #{pr_number}:** {title}\n\n"
            f"**Verdict:** {verdict} | **Confidence:** {conf:.0%}\n\n"
        )
        if issues:
            body += "### Issues Found\n" + "\n".join(f"- {i}" for i in issues) + "\n\n"
        body += f"### Full Analysis\n{report[:2000]}\n\n"
        body += "_Generated by AILEX Pilot_"

        return PRReview(
            pr_number=pr_number, title=title, diff_summary=diff[:500],
            issues=issues, suggestions=[], security=[],
            verdict=verdict, confidence=conf, body=body,
        )

    def _extract_issues(self, report: str) -> List[str]:
        issues = []
        for line in report.split("\n"):
            if any(w in line.lower() for w in ["risk", "issue", "bug", "security", "⚠", "missing test"]):
                clean = re.sub(r"^\s*[-•*]\s*", "", line.strip())
                if 10 < len(clean) < 200:
                    issues.append(clean)
        return issues[:5]

    def _post_review(self, pr_number: int, review: PRReview, repo: str) -> bool:
        cmd = ["gh", "pr", "review", str(pr_number),
               f"--{review.verdict.lower().replace('_', '-')}",
               "--body", review.body]
        if repo:
            cmd += ["--repo", repo]
        r = subprocess.run(cmd, capture_output=True, text=True)
        return r.returncode == 0
