"""
AILEX — api_autodiscovery.py
Auto-generate integrations from any OpenAPI/Swagger spec.
Paste a URL to an API spec → AILEX generates the full integration.
"""
from __future__ import annotations
import re,json,os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

@dataclass
class APIIntegration:
    name:     str
    base_url: str
    language: str
    client:   str    # generated client code
    tests:    str    # generated tests
    docs:     str    # generated usage docs
    endpoints: int

class APIAutoDiscovery:
    """Auto-generate SDK clients from OpenAPI specs."""

    def discover(self, spec_url: str, language: str = "typescript",
                 client: Any = None) -> APIIntegration:
        import urllib.request
        try:
            with urllib.request.urlopen(spec_url, timeout=15) as r:
                spec = json.loads(r.read())
        except Exception as e:
            return APIIntegration(spec_url, "", language, f"# Error: {e}", "", "", 0)

        title    = spec.get("info", {}).get("title", "API")
        base_url = spec.get("servers", [{}])[0].get("url", "")
        paths    = spec.get("paths", {})
        endpoints= len(paths)

        if client:
            prompt = (
                f"Generate a complete {language} SDK client for this API:\n"
                f"Name: {title}\nBase URL: {base_url}\n"
                f"Endpoints: {json.dumps(list(paths.keys())[:10])}\n\n"
                "Include: typed interfaces, error handling, retry logic, auth.\n"
                "Return ONLY the code."
            )
            resp = client.messages.create(
                model="claude-sonnet-4-6", max_tokens=4000,
                messages=[{"role":"user","content":prompt}])
            code = resp.content[0].text
        else:
            code = f"// {title} SDK Client ({language})\n// Generated by AILEX APIAutoDiscovery\n// Base URL: {base_url}\n// {endpoints} endpoints\n\nexport class {re.sub(r'[^a-zA-Z]','',title)}Client {{\n  constructor(private apiKey: string) {{}}\n}}"

        return APIIntegration(title, base_url, language, code, "", f"# {title} Integration\n\nGenerated by AILEX", endpoints)


"""
AILEX — visual_regression.py
Screenshot before/after code changes. Detect visual regressions automatically.
"""
@dataclass
class VisualDiff:
    before:   Optional[str]   # path to before screenshot
    after:    Optional[str]   # path to after screenshot
    changed:  bool
    diff_pct: float           # percentage of pixels changed
    regions:  List[str]       # changed regions description

class VisualRegressionTester:
    """Detect visual regressions via screenshot comparison."""

    SAVE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "visual_snapshots")

    def __init__(self):
        os.makedirs(self.SAVE_DIR, exist_ok=True)

    def snapshot(self, url: str, label: str = "snapshot") -> Optional[str]:
        """Take a screenshot of a URL."""
        try:
            from playwright.sync_api import sync_playwright
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                page    = browser.new_page(viewport={"width":1440,"height":900})
                page.goto(url, wait_until="networkidle", timeout=20000)
                path = os.path.join(self.SAVE_DIR, f"{label}_{int(__import__('time').time())}.png")
                page.screenshot(path=path, full_page=True)
                browser.close()
                return path
        except Exception:
            return None

    def compare(self, before: str, after: str) -> VisualDiff:
        """Compare two screenshots pixel-by-pixel."""
        try:
            from PIL import Image, ImageChops
            import numpy as np
            img1 = Image.open(before).convert("RGB")
            img2 = Image.open(after).convert("RGB")
            if img1.size != img2.size:
                img2 = img2.resize(img1.size)
            diff  = ImageChops.difference(img1, img2)
            arr   = np.array(diff)
            changed_pixels = np.sum(arr > 10)
            total_pixels   = arr.size // 3
            pct = changed_pixels / max(1, total_pixels) * 100
            return VisualDiff(before=before, after=after, changed=pct>0.5, diff_pct=round(pct,2), regions=[])
        except Exception as e:
            return VisualDiff(before=before, after=after, changed=False, diff_pct=0.0, regions=[str(e)])


"""
AILEX — performance_loop.py
Continuous profiling and optimization loop.
"""
import subprocess, time as _time

@dataclass
class PerformanceProfile:
    file:      str
    hotspots:  List[str]
    suggestions: List[str]
    estimated_speedup: str

class PerformanceLoop:
    """Profile → identify hotspots → generate optimizations → measure improvement."""

    def profile_python(self, script: str, args: List[str] = []) -> PerformanceProfile:
        """Profile a Python script and return hotspots."""
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".py", delete=False, mode="w") as f:
            f.write(script); path = f.name
        try:
            r = subprocess.run(
                ["python3", "-m", "cProfile", "-s", "cumulative", path] + args,
                capture_output=True, text=True, timeout=30
            )
            output = r.stdout + r.stderr
            # Parse top functions
            lines = [l for l in output.split("\n") if re.match(r"\s+\d+", l)][:5]
            hotspots = [re.sub(r"\s+", " ", l).strip() for l in lines]
            suggestions = ["Use list comprehensions instead of loops",
                          "Cache repeated computations", "Use generators for large datasets"]
            return PerformanceProfile(path, hotspots, suggestions, "10-40% estimated")
        except Exception as e:
            return PerformanceProfile(script[:30], [], [str(e)], "unknown")
        finally:
            os.unlink(path) if os.path.exists(path) else None

    def optimize(self, code: str, profile: PerformanceProfile, client: Any = None) -> str:
        """Generate optimized version based on profile."""
        if not client:
            return code  # demo mode
        resp = client.messages.create(
            model="claude-sonnet-4-6", max_tokens=3000,
            messages=[{"role":"user","content":
                f"Optimize this code based on profiling:\nHotspots: {profile.hotspots}\n\n```python\n{code[:2000]}\n```\nReturn optimized code only."}])
        return resp.content[0].text


# Export everything
from typing import TYPE_CHECKING
__all__ = ["APIAutoDiscovery", "APIIntegration", "VisualRegressionTester", "VisualDiff",
           "PerformanceLoop", "PerformanceProfile"]
